spring:  
    profiles: prod
    datasource:            
        initialization-mode: always       
        username: root
        password: Everest8848
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/resumebase
        
---
spring:  
    profiles: test
    datasource:
        schema: classpath*:database/initBD.sql
        data: classpath*:database/populateDB.sql 
        initialization-mode: always
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/resumebasetest
        username: root
        password: Everest8848   
   
